# Originally generated by ChatGPT, corrected/verified by T. Campbell.
#
# Changed for the Chinese edition: the upstream version hardcoded
# https://python.datasciencebook.ca/ as the canonical URL of every page, which is
# correct for the authors' own English site but wrong for a translation. A canonical
# link that points at another language tells search engines "the authoritative copy of
# this page is that one", so the Chinese pages would be treated as duplicates of the
# English ones and dropped from the index. (Cross-language equivalents are expressed
# with hreflang, not canonical.)
#
# The base URL is therefore explicit: pass --base-url, or set DOCS_BASE_URL. With no base
# URL the script removes any canonical link it finds and adds nothing, which is the safe
# default for a fork that is not being published anywhere in particular.

import argparse
import os
import re
from pathlib import Path

DOCS_DIR = Path("source/_build/html")
CANONICAL_RE = re.compile(r'^[ \t]*<link rel="canonical"[^>]*>[ \t]*\r?\n?', re.MULTILINE)


def update_html_file(path: Path, base_url: str | None) -> str:
    html = path.read_text(encoding="utf-8")
    had = bool(CANONICAL_RE.search(html))
    html = CANONICAL_RE.sub("", html)

    if base_url:
        line = f'<link rel="canonical" href="{base_url.rstrip("/")}/{path.name}" />'
        match = re.search(r"<head\b[^>]*>", html, re.IGNORECASE)
        if not match:
            return f"Skipping (no <head> found): {path}"
        html = html[: match.end()] + "\n" + line + html[match.end():]
        path.write_text(html, encoding="utf-8")
        return f"{'Replaced' if had else 'Added'} canonical -> {path}"

    if had:
        path.write_text(html, encoding="utf-8")
        return f"Removed stale canonical: {path}"
    return f"Unchanged: {path}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default=os.environ.get("DOCS_BASE_URL", ""))
    ap.add_argument("--docs-dir", type=Path, default=DOCS_DIR)
    args = ap.parse_args()

    base_url = args.base_url or None
    if base_url:
        print(f"canonical base URL: {base_url}")
    else:
        print("no --base-url / DOCS_BASE_URL: removing canonical links, adding none")

    count = 0
    # Top-level pages only. Walking recursively would also reach Sphinx's HTML *templates*
    # under _static/ (they have no <head>, so nothing happens, but they are not pages and
    # a canonical link has no business in them).
    for path in sorted(args.docs_dir.glob("*.html")):
        if update_html_file(path, base_url):
            count += 1
    print(f"processed {count} html page(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())